# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20170510_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='yurchikurl',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
