# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-15 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0005_auto_20170513_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yurchikurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener.validators.validate_dot_com, shortener.validators.validate_url]),
        ),
    ]
